import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val com_github_chuckerteam_chucker: String = "3.1.2" // available: "3.2.0"

    const val androidx_test_espresso: String = "3.2.0"

    const val com_squareup_retrofit2: String = "2.7.2" // available: "2.8.1"

    const val com_squareup_okhttp3: String = "4.4.0" // available: "4.5.0"

    const val androidx_navigation: String = "2.2.1" // available: "2.2.2"

    const val com_google_dagger: String = "2.26" // available: "2.27"

    const val androidx_test: String = "1.2.0"

    const val com_android_tools_build_gradle: String = "3.6.1" // available: "3.6.3"

    const val androidx_test_ext_junit: String = "1.1.1"

    const val junit_junit: String = "4.13"

    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.7.0"

    const val kotlin_scripting_compiler_embeddable: String = "1.3.61" // available: "1.3.71"

    const val kotlin_annotation_processing_gradle: String = "1.3.61" // available: "1.3.71"

    const val kotlin_android_extensions_runtime: String = "1.3.61" // available: "1.3.71"

    const val kotlin_android_extensions: String = "1.3.61" // available: "1.3.71"

    const val keyboardvisibilityevent: String = "2.3.0"

    const val kotlin_gradle_plugin: String = "1.3.71" // available: "1.3.72"

    const val lifecycle_extensions: String = "2.2.0"

    const val kotlin_stdlib_jdk7: String = "1.3.61" // available: "1.3.71"

    const val constraintlayout: String = "1.1.3"

    const val core_testing: String = "2.1.0"

    const val recyclerview: String = "1.1.0"

    const val lint_gradle: String = "26.6.1" // available: "26.6.3"

    const val appcompat: String = "1.1.0"

    const val rxandroid: String = "2.1.1"

    const val cardview: String = "1.0.0"

    const val core_ktx: String = "1.2.0"

    const val picasso: String = "2.71828"

    const val rxjava: String = "2.2.19"

    const val aapt2: String = "3.6.1-6040484" // available: "3.6.3-6040484"

    const val mockk: String = "1.9.3"

    /**
     * Current version: "5.6.4"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "6.3"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
            id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
